"""Research utilities for theory-neutral consciousness measurement science."""

from .evidence import EvidenceChannel, fuse_independent_channels, posterior_from_lr
from .identification_design import (
    MultiSiteIdentifiedSet,
    hoeffding_resolution_sample_size,
    independent_gate_preserves_conditional_coverage,
    interior_missingness_width,
    missingness_resolution_interval_known_calibration,
    multisite_average_prevalence_identified_interval,
    pooled_average_is_point_identified,
    pooled_average_prevalence_if_identified,
)
from .latent_measurement import (
    CalibrationBox,
    RateInterval,
    calibration_box_prevalence_outer_interval,
    finite_sample_prevalence_outer_interval,
    hoeffding_rate_interval,
    latent_effect_from_proxy_effect,
    latent_prevalence_from_proxy_rate,
    proxy_rate_from_latent_prevalence,
    transport_bias_from_calibration_shift,
    youden_index,
)
from .measurement_robustness import (
    LocalInversionSensitivity,
    TwoSiteIdentifiedSet,
    inverse_slope_amplification,
    joint_finite_sample_prevalence_outer_interval,
    local_inversion_sensitivities,
    missingness_proxy_rate_bounds,
    missingness_robust_prevalence_outer_interval,
    pooled_two_site_proxy_rate,
    two_site_average_prevalence_identified_interval,
)
from .partial_identification import (
    DependenceRobustFusion,
    LikelihoodRatioInterval,
    ProbabilityInterval,
    conditional_pattern_probability_bounds,
    frechet_intersection_bounds,
    fuse_unknown_dependence,
    likelihood_ratio_bounds,
    posterior_interval_from_lr_bounds,
)
from .profile import (
    ChannelEvidence,
    ConsciousnessEvidenceProfile,
    InferenceState,
    Target,
)
from .structural_alignment import (
    distance_matrix,
    matrix_alignment,
    normalized_distortion,
    permutation_alignment_test,
)

__all__ = [
    "CalibrationBox",
    "ChannelEvidence",
    "ConsciousnessEvidenceProfile",
    "DependenceRobustFusion",
    "EvidenceChannel",
    "InferenceState",
    "LikelihoodRatioInterval",
    "LocalInversionSensitivity",
    "MultiSiteIdentifiedSet",
    "ProbabilityInterval",
    "RateInterval",
    "Target",
    "TwoSiteIdentifiedSet",
    "calibration_box_prevalence_outer_interval",
    "conditional_pattern_probability_bounds",
    "distance_matrix",
    "finite_sample_prevalence_outer_interval",
    "frechet_intersection_bounds",
    "fuse_independent_channels",
    "fuse_unknown_dependence",
    "hoeffding_rate_interval",
    "hoeffding_resolution_sample_size",
    "independent_gate_preserves_conditional_coverage",
    "interior_missingness_width",
    "inverse_slope_amplification",
    "joint_finite_sample_prevalence_outer_interval",
    "latent_effect_from_proxy_effect",
    "latent_prevalence_from_proxy_rate",
    "likelihood_ratio_bounds",
    "local_inversion_sensitivities",
    "matrix_alignment",
    "missingness_proxy_rate_bounds",
    "missingness_resolution_interval_known_calibration",
    "missingness_robust_prevalence_outer_interval",
    "multisite_average_prevalence_identified_interval",
    "normalized_distortion",
    "permutation_alignment_test",
    "pooled_average_is_point_identified",
    "pooled_average_prevalence_if_identified",
    "pooled_two_site_proxy_rate",
    "posterior_from_lr",
    "posterior_interval_from_lr_bounds",
    "proxy_rate_from_latent_prevalence",
    "transport_bias_from_calibration_shift",
    "two_site_average_prevalence_identified_interval",
    "youden_index",
]
